from robot_hat import Music, set_volume
import time

# Create a new Music object
music = Music()

set_volume(80)
music.tempo(60, 1/4)

print("Measure 1")
music.play_tone_for(music.note("G4"), music.beat(1/8))
print("Measure 2")
music.play_tone_for(music.note("A#4"), music.beat(1/4))
music.play_tone_for(music.note("C5"), music.beat(1/8))
music.play_tone_for(music.note("D5"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("D#5"), music.beat(1/16))
music.play_tone_for(music.note("D5"), music.beat(1/8))
print("Measure 3")
music.play_tone_for(music.note("C5"), music.beat(1/4))
music.play_tone_for(music.note("A4"), music.beat(1/8))
music.play_tone_for(music.note("F4"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("G4"), music.beat(1/16))
music.play_tone_for(music.note("A4"), music.beat(1/8))
print("Measure 4")
music.play_tone_for(music.note("A#4"), music.beat(1/4))
music.play_tone_for(music.note("G4"), music.beat(1/8))
music.play_tone_for(music.note("G4"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("F#4"), music.beat(1/16))
music.play_tone_for(music.note("G4"), music.beat(1/8))
print("Measure 5")
music.play_tone_for(music.note("A4"), music.beat(1/4))
music.play_tone_for(music.note("F#4"), music.beat(1/8))
music.play_tone_for(music.note("D4"), music.beat(1/4))
music.play_tone_for(music.note("G4"), music.beat(1/8))
print("Measure 6")
music.play_tone_for(music.note("A#4"), music.beat(1/4))
music.play_tone_for(music.note("C5"), music.beat(1/8))
music.play_tone_for(music.note("D5"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("D#5"), music.beat(1/16))
music.play_tone_for(music.note("D5"), music.beat(1/8))
print("Measure 7")
music.play_tone_for(music.note("C5"), music.beat(1/4))
music.play_tone_for(music.note("A4"), music.beat(1/8))
music.play_tone_for(music.note("F4"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("G4"), music.beat(1/16))
music.play_tone_for(music.note("A4"), music.beat(1/8))
print("Measure 8")
music.play_tone_for(music.note("A#4"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("A4"), music.beat(1/16))
music.play_tone_for(music.note("G4"), music.beat(1/8))
music.play_tone_for(music.note("F#4"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("E4"), music.beat(1/16))
music.play_tone_for(music.note("F#4"), music.beat(1/8))
print("Measure 9")
music.play_tone_for(music.note("G4"), music.beat(1/4 + 1/8))
music.play_tone_for(music.note("G4"), music.beat(1/4 + 1/8))
print("Measure 10")
music.play_tone_for(music.note("F5"), music.beat(1/4 + 1/8))
music.play_tone_for(music.note("F5"), music.beat(1/8))
music.play_tone_for(music.note("E5"), music.beat(1/16))
music.play_tone_for(music.note("D5"), music.beat(1/8))
print("Measure 11")
music.play_tone_for(music.note("C5"), music.beat(1/4))
music.play_tone_for(music.note("A4"), music.beat(1/8))
music.play_tone_for(music.note("F4"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("G4"), music.beat(1/16))
music.play_tone_for(music.note("A4"), music.beat(1/8))
print("Measure 12")
music.play_tone_for(music.note("A#4"), music.beat(1/4))
music.play_tone_for(music.note("G4"), music.beat(1/8))
music.play_tone_for(music.note("G4"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("F#4"), music.beat(1/16))
music.play_tone_for(music.note("G4"), music.beat(1/8))
print("Measure 13")
music.play_tone_for(music.note("A4"), music.beat(1/4))
music.play_tone_for(music.note("F#4"), music.beat(1/8))
music.play_tone_for(music.note("D4"), music.beat(1/4 + 1/8))
print("Measure 14")
music.play_tone_for(music.note("F5"), music.beat(1/4 + 1/8))
music.play_tone_for(music.note("F5"), music.beat(1/8))
music.play_tone_for(music.note("E5"), music.beat(1/16))
music.play_tone_for(music.note("D5"), music.beat(1/8))
print("Measure 15")
music.play_tone_for(music.note("C5"), music.beat(1/4))
music.play_tone_for(music.note("A4"), music.beat(1/8))
music.play_tone_for(music.note("F4"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("G4"), music.beat(1/16))
music.play_tone_for(music.note("A4"), music.beat(1/8))
print("Measure 16")
music.play_tone_for(music.note("A#4"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("A4"), music.beat(1/16))
music.play_tone_for(music.note("G4"), music.beat(1/8))
music.play_tone_for(music.note("F#4"), music.beat(1/8 + 1/16))
music.play_tone_for(music.note("E4"), music.beat(1/16))
music.play_tone_for(music.note("F#4"), music.beat(1/8))
print("Measure 17")
music.play_tone_for(music.note("G4"), music.beat(1/4 + 1/8))
music.play_tone_for(music.note("G4"), music.beat(1/4 + 1/8))


# Baby shark

# music.tempo(180)
# music.key_signature("#")
# music.time_signature(4, 4)

# print("Measure 0")
# music.play_tone_for(music.note("D4"), music.beat(1/2))
# music.play_tone_for(music.note("E4"), music.beat(1/2))
# print("Measure 1")
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# print("Measure 2")
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("D4"), music.beat(1/4))
# music.play_tone_for(music.note("E4"), music.beat(1/4))
# print("Measure 3")
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# print("Measure 4")
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("D4"), music.beat(1/4))
# music.play_tone_for(music.note("E4"), music.beat(1/4))
# print("Measure 5")
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# print("Measure 6")
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# music.play_tone_for(music.note("G4"), music.beat(1/8))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# music.play_tone_for(music.note("G4"), music.beat(1/4))
# print("Measure 7")
# music.play_tone_for(music.note("F#4"), music.beat(1))
